### ISSUE TITLE
Add topics to repository

### ISSUE THREAD

**Issue by impulse** [flame-engine/awesome-flame#10]
From: https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

> The repo should have awesome-list & awesome as GitHub topics. I encourage you to add more relevant topics.

**Comment by luanpotter** [comment]
I had added a few, including `awesome`. I added now `awesome-list`. Do you have more topics in mind to add?

**Comment by impulse** [comment]
The awesome repo also has:
lists
resources

But looks good  already 👌

**Comment by luanpotter** [comment]
Added both ;)
