### ISSUE TITLE
Submit PR to official awesome repo

### ISSUE THREAD

**Issue by impulse** [flame-engine/awesome-flame#28]
Since the list has quite matured we could now think about making it an official awesome repo:
https://github.com/sindresorhus/awesome/blob/master/create-list.md

TODO:
- [x] Check if repo complies with awesome manifesto
- [x] Check if repo complies the awesome guidelines

**Comment by erickzanardo** [comment]
Sounds good

**Comment by luanpotter** [comment]
Man, I was planning on asking you precisely about that!!! I think it would be awesome (pun intended) to be on the awesome awesome list. However they are *very* strict with guidelines so we might have a  hard time. I was gonna ask if we had spent any time already making sure we are acceptable for them.

**Comment by erickzanardo** [comment]
> awesome awesome list

awesome 🤔

**Comment by impulse** [comment]
> Man, I was planning on asking you precisely about that!!! I think it would be awesome (pun intended) to be on the awesome awesome list. However they are _very_ strict with guidelines so we might have a hard time. I was gonna ask if we had spent any time already making sure we are acceptable for them.

I already checked with the formatting tool and the general guidelines back when we made this repo. Yet back then we didn't have the minimum age of the repo to be able to submit a PR. I'll take a look at the guidelines again tomorrow and report back. @luanpotter @erickzanardo  want me to handle the PR on the awesome repo?

**Comment by erickzanardo** [comment]
@impulse Yes please
