### ISSUE TITLE
can not open tutorial website cause by SSL error

### ISSUE THREAD

**Issue by ainomegumi-desu** [flame-engine/awesome-flame#75]
hello @Yayo-Arellano, thanks for your tutorial, feel bad to bother you, the website can not be accessed caused by SSL error

such as https://yayocode.com/post/XPECczhhAZgJDGcy69AO

http: error: SSLError: HTTPSConnectionPool(host='yayocode.com', port=443): Max retries exceeded with url: /post/XPECczhhAZgJDGcy69AO (Caused by SSLError(SSLCertVerificationError("hostname 'yayocode.com' doesn't match either of 'firebaseapp.com', '*.firebaseapp.com'"))) while doing GET request to URL: https://yayocode.com/post/XPECczhhAZgJDGcy69AO

**Comment by Yayo-Arellano** [comment]
I have updated the certificate. It may take some time for them to propagate. As a workaround (for now), please add `www` at the start like this=> https://www.yayocode.com/post/XPECczhhAZgJDGcy69AO
