### ISSUE TITLE
Add Oderrube Game

### ISSUE THREAD

**Issue by pcgoncalves42** [flame-engine/awesome-flame#92]
Oderrube is an exciting physics puzzle game. Carefully remove the blocks to allow Derrubito to fall into the target. 

https://play.google.com/store/apps/details?id=br.com.pcgoncalves.oderrube

https://apps.apple.com/br/app/oderrube/id6447583342?platform=iphone

Paulo Gonçalves (https://www.linkedin.com/in/opaulogoncalves)

**Comment by pcgoncalves42** [comment]
I'm still getting the hang of things here on GitHub, so I'm not sure if your comment is a suggestion for what I should do or an indication that I did something wrong.

**Comment by ufrshubham** [comment]
I was asking if you would like to add `Oderrube` to this repo yourself. Normally, the original authors of the games add their game to the list by modifying the readme file and creating a pull request for it. You can read the [CONTRIBUTING.md](https://github.com/flame-engine/awesome-flame/blob/main/CONTRIBUTING.md) to understand how to add new entries. You can also check some of the closed PRs that added new game entries here: https://github.com/flame-engine/awesome-flame/pulls?q=is%3Apr+is%3Aclosed
